const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";
CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

CONSTANTS.ENDPOINT.GRID = "/grid";

CONSTANTS.ENDPOINT.LIST = "/list";


module.exports = CONSTANTS;
